spring.datasource.url=jdbc:mysql://localhost:3306/estudante_db?createDatabaseIfNotExist=true

# Suas credenciais (conforme vimos no teste do DBeaver)
spring.datasource.username=root
spring.datasource.password=root

# Dialeto e Auto-update (isso vai criar as tabelas sozinho ao rodar o projeto)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true