# Configuração da Conexão com o Banco de Dados MySQL (XAMPP)
spring.datasource.url=jdbc:mysql://localhost:3306/estudante_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
# No XAMPP a senha padrão é vazia. Não coloque nada depois do "=":
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Ativa o reload automático ao alterar o código
spring.devtools.restart.enabled=true